version: '3.3'

volumes:
  pg_data:
  static:
  media:
  redoc:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data


  backend:
    image: trubnss/foodgram_backend
    env_file: ../.env
    volumes:
      - static:/backend_static/
      - media:/app/media
      - redoc:/app/api/docs/
    depends_on:
      - db
      - frontend

  frontend:
    image: trubnss/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
      - static:/var/html/staticfiles/
      - media:/var/html/media
    depends_on:
      - backend
      - frontend
      - db