# Generated by Django 4.2.8 on 2024-02-03 18:32

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024,
                    2,
                    3,
                    18,
                    32,
                    57,
                    947142,
                    tzinfo=datetime.timezone.utc,
                ),
            ),
            preserve_default=False,
        ),
    ]
