# Generated by Django 4.2.8 on 2024-02-05 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_recipetag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecipeTag",
        ),
    ]
